from __future__ import annotations

import json
from pathlib import Path

from builder_agent.core.models import AgentSpec, BuilderConfig


class AgentGenerator:
    def __init__(self, cfg: BuilderConfig) -> None:
        self.cfg = cfg

    def generate(self, spec: AgentSpec) -> Path:
        root = self.cfg.paths.generated_agents_dir / spec.name
        (root / "config").mkdir(parents=True, exist_ok=True)
        (root / "workspace").mkdir(parents=True, exist_ok=True)
        (root / "skills").mkdir(parents=True, exist_ok=True)
        (root / "tests").mkdir(parents=True, exist_ok=True)

        openclaw_config = {
            "gateway": {"mode": "local", "bind": "localhost"},
            "agents": {
                "defaults": {
                    "model": {"primary": spec.model_primary},
                    "workspace": str(spec.workspace_path),
                },
                "list": [{"id": spec.name, "default": True}],
            },
            "skills": {
                "entries": {k: {"enabled": True} for k in spec.skills},
                "load": {"extraDirs": [str(root / "skills")]},
            },
            "channels": spec.channels,
            "cron": {"enabled": True, "maxConcurrentRuns": 1},
        }

        (root / "config" / "openclaw.json").write_text(json.dumps(openclaw_config, indent=2))
        (root / "README.md").write_text(self._readme(spec))
        (root / "workspace" / "AGENTS.md").write_text(self._agents_md(spec))
        (root / "workspace" / "IDENTITY.md").write_text(f"# Identity\n\n- Agent: {spec.name}\n")
        (root / "tests" / "test_smoke.py").write_text(self._smoke_test(spec.name))
        return root

    def _readme(self, spec: AgentSpec) -> str:
        return (
            f"# {spec.name}\n\n"
            f"{spec.description}\n\n"
            "Generated by Builder (OpenClaw-native).\n"
        )

    def _agents_md(self, spec: AgentSpec) -> str:
        return (
            "# Agent Rules\n\n"
            f"You are {spec.name}.\n\n"
            "- Follow OpenClaw lifecycle and deterministic execution.\n"
            "- Keep secrets externalized (Doppler recommended).\n"
        )

    def _smoke_test(self, name: str) -> str:
        return (
            "from pathlib import Path\n\n"
            "def test_generated_layout():\n"
            "    root = Path(__file__).resolve().parents[1]\n"
            "    assert (root / 'config' / 'openclaw.json').exists()\n"
            "    assert (root / 'workspace' / 'AGENTS.md').exists()\n"
            f"    assert (root / 'README.md').read_text().startswith('# {name}')\n"
        )
